version: "3.3"
services:
  db:
      image: mariadb:latest
      volumes:
          - type: bind
            source: /var/vm/db
            target: /var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: app 
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: votedb
      ports:
          - target: 3306
            published: 3306
            protocol: tcp
            mode: host